---
- name: Start Docker Container
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: nginx:latest
        source: pull

    - name: Start Docker Container
      docker_container:
        name: my_nginx_container
        image: nginx:latest
        state: started
        ports:
          - "8080:80"
