---
- name: Deploy Nginx Container
  hosts: web_servers
  gather_facts: false

  tasks:
    - name: Pull a random nginx image
      docker_image:
        name: nginx:latest
        source: pull

    - name: Run nginx container
      docker_container:
        name: my_nginx_container
        image: nginx:latest
        state: started
        ports:
          - "80:80"
